### ISSUE TITLE
Ability to force newline at end of request body

### ISSUE THREAD

**Issue by jimmcslim** [Huachao/vscode-restclient#292]
The Elasticsearch Bulk API requires that the request body have a final newline character. However it seems that VS Code REST Client trims leading and trailing whitespace from the request body, which I agree is a reasonable thing to do.

However, without the final newline character in this case, Elasticsearch ignores the last record in the bulk update operation.

It would be good if there was a simple way to specify to VS Code REST Client that some whitespace is actually significant!

**Comment by Huachao** [comment]
@jimmcslim @michelemauro so in this case the content type header of request body should be Content-Type: application/x-ndjson, right ?

**Comment by jimmcslim** [comment]
Yes, that appears to be the case.

**Comment by Huachao** [comment]
@jimmcslim @michelemauro @esurijon I have fixed the issue that append a newline character to the end of the request body for `x-ndjson` MIME type. And this fix will be published in next release.

**Comment by Huachao** [comment]
@jimmcslim @michelemauro @esurijon you can try the latest version to verify

**Comment by vangavenunath** [comment]
Still getting error - "The bulk request must be terminated by a newline [\\n]" on version `0.24.6`

```
POST https://<aws opensearch url>/_bulk
content-type: application/x-ndjson

{ "index": { "_index": "movies", "_type": "movie", "_id": "tt2229499" } }
{"directors":["Joseph Gordon-Levitt"],"release_date":"2013-01-18T00:00:00Z","rating":7.4,"genres":["Comedy","Drama"],"image_url":"https://m.media-amazon.com/images/M/MV5BMTQxNTc3NDM2MF5BMl5BanBnXkFtZTcwNzQ5NTQ3OQ@@._V1_SX400_.jpg","plot":"A New Jersey guy dedicated to his family, friends, and church, develops unrealistic expectations from watching porn and works to find happiness and intimacy with his potential true love.","title":"Don Jon","rank":1,"running_time_secs":5400,"actors":["Joseph Gordon-Levitt","Scarlett Johansson","Julianne Moore"],"year":2013,"id":"tt2229499","type":"add"}

```
