### ISSUE TITLE
WARN: command 'rest-client.request' not found (and nothing happens)

### ISSUE THREAD

**Issue by sfertman** [Huachao/vscode-restclient#38]
- VSCode Version: 1.5.2
- OS Version: Ubuntu 15.10
- REST Client Version: 0.8.0 (used to work fine before latest update)

Steps to Reproduce: 
Run (Ctrl+Alt+R) the following (or any other for that matter)

GET https://example.com/ HTTP/1.1

**Comment by Huachao** [comment]
@sfertman , we have found the root cause that require file with upper case name. Thanks so much for the help of @myakimov. I have published a new version 0.8.1, could you please have a try?

**Comment by Huachao** [comment]
@sfertman the issue is fixed in latest version 0.8.1 with the help of @myakimov, could you please try it 😸

**Comment by sfertman** [comment]
Awesome! Thanks guys!

**Comment by tabishsoh** [comment]
Hi I am facing the same issue. Installed the extention from VS and restarted many times still facing the same issue.
