### ISSUE TITLE
Shared variables are no longer accessible when selecting "No Environment" after update

### ISSUE THREAD

**Issue by atrakaz** [Huachao/vscode-restclient#420]
- VSCode Version: 1.38.1
- OS Version: Windows 10 Pro
- REST Client Version: 0.22.1
Note: Worked yesterday before the new version

Steps to Reproduce:

1. ...>AppData>Roaming>Code>User>settings.json:
"rest-client.environmentVariables": {
        "emptyEnvironment": {
        },
        "$shared": {
            "testUrl": "http://www.google.com/"
        },
}

2. Select REST Client Environment: "No Environment"

3. test.http:
###
GET {{testUrl}}

=> Error message: "Cannot convert undefined or null to object"
![error](https://user-images.githubusercontent.com/20646814/65229740-0cd5cd80-dacd-11e9-820e-cfe53f8aa5a1.png)

4. 
When selecting "emptyEnvironment", Shared variables are accessible.

Conclusion:
This breaks the following statement when selecting the following: "No environment (You Can Still Use Variables Defined In $shared Environment)"

**Comment by Huachao** [comment]
@atrakaz nice catch, I have fixed the issue and will be published in next release 😄

**Comment by jezikk** [comment]
@Huachao When this bugfix will be published in production please? I started VSCode today and the error message is still shown. Shared environments are not available in my project.

**Comment by Huachao** [comment]
@jezikk version 0.22.1 is not totally ready, I am still working on some other features, and after that the 0.22.1 will be published

**Comment by jezikk** [comment]
It's weird, but I already have version 0.22.1 installed.

![image](https://user-images.githubusercontent.com/7671531/65312924-c1d2bd80-db93-11e9-88c8-cadb3a3f90dc.png)

**Comment by Huachao** [comment]
@jezikk sorry the upcoming release version should be **0.22.2**

**Comment by Huachao** [comment]
@jezikk @atrakaz  you can try the latest version 0.22.2 to verify it.

**Comment by jezikk** [comment]
It's oka now. Thanks!

**Comment by atrakaz** [comment]
It works. Thanks!

**Comment by cedx** [comment]
This issue is still here with VSCode 1.45.0 in Windows 10 (x64) with REST Client 0.23.2.

**Comment by Huachao** [comment]
@cedx I can't repro your case, could you please double-check the defined shared environment variables in your settings and the referenced variable name in your `.http` file?
