### ISSUE TITLE
followRedirect: true is not working

### ISSUE THREAD

**Issue by vigilancer** [Huachao/vscode-restclient#948]
Option "followRedirect: true" is not working.

#### How to reproduce

add something like this to file with `.http` extension and run request with this plugin from VS Code.
```
POST /auth/login HTTP/1.1
Host: api.XXX

{"username":"test@test.te","password":"test"}
```
`api.XXX` should be changed with appropriate example. I'm working with private API and cannot share details but any endpoint that answers with 301 will do.

#### Solution

I've spend some time debugging and seems to be the problem is in the `got` library.
Apparently `got@9.6.0` does not respect `followRedirect` flag that plugin is passing to it.
Last version `got@12.0.0` on the other hand do respect `followRedirect`.

Here are some code that you could try and see it for yourself:

`got@9.6.0`:
```
const url = 'http://api.XXX/auth/login'
const response = await got.post(url, {
	body: {
		username: 'XXX',
               password: 'XXX'
	},
    json: true,
    followRedirect: true,
})
console.log(response.statusCode, "\n", response.rawHeaders);
```

`got@12.0.0`:
```
const url = 'http://api.XXX/auth/login'
const response = await got.post(url, {
	json: {
        username: 'XXX',
        password: 'XXX'
	},
   followRedirect: true,
});
console.log(response.statusCode, "\n", response.rawHeaders);
```

Are you planing to update the `got` library?
They've changed API since then but nothing critical AFAIK and this seems quite doable.

- REST Client Version: 0.24.6
- VSCode Version:  1.63.2

**Comment by AnWeber** [comment]
[got 12](https://github.com/sindresorhus/got/issues/1789) switched to esm. See https://github.com/sindresorhus/got/issues/1789. [Rest client](https://github.com/Huachao/vscode-restclient/blob/master/tsconfig.json#L3) is commonjs. Switching to esm is doable, but needs some time. Maybe try got 11 which also supports followRedirect correctly. Tested with my own extension.

**Comment by vigilancer** [comment]
Nice catch, thank you.

I'm ready to invest some time.  @Huachao will you consider PR with `got` upgrade from 9.6 to 11?

**Comment by Huachao** [comment]
@vigilancer of course, just ensure it is well tested :)

**Comment by codeConcussion** [comment]
It appears I'm hitting this issue with POST requests. Is there a work around?

**Comment by Huachao** [comment]
Fixed by upgrading got library to v11.8.6

**Comment by marlon-sousa** [comment]
It seems though that for post requests it still does not work as #981.

I could confirm this when trying to test, I am with 0.25.1 installed.

**Comment by AnWeber** [comment]
@marlon-sousa no release since mid 2022.
